import { Job } from "@/interfaces";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Google",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_%22G%22_logo.svg/768px-Google_%22G%22_logo.svg.png",
    location: "Mountain View, CA",
    salaryRange: "$150k - $220k",
    type: "Full-Time",
    experience: "Senior",
    tags: ["Remote", "TypeScript", "React"],
    postedDate: "2024-03-10",
    isRemote: true,
    description:
      "We are looking for a seasoned Senior Frontend Engineer to join our dynamic team. You will be responsible for building the client-side of our web applications.",
    responsibilities: [
      "Develop new user-facing features using React.js.",
      "Build reusable components and front-end libraries for future use.",
      "Translate designs and wireframes into high-quality code.",
      "Optimize components for maximum performance.",
    ],
    requirements: [
      "Strong proficiency in JavaScript and the DOM.",
      "Thorough understanding of React.js and core principles.",
      "Experience with Flux or Redux workflows.",
    ],
    benefits: [
      "Competitive salary and equity package.",
      "Comprehensive health, dental, and vision insurance.",
      "401(k) plan with company match.",
    ],
  },
  {
    id: "2",
    title: "Full-Stack Developer",
    company: "Tech Solutions",
    logo: "https://cdn-icons-png.flaticon.com/512/10096/10096298.png", // Generic tech logo
    location: "New York, NY",
    salaryRange: "$120k - $160k",
    type: "Full-Time",
    experience: "Mid",
    tags: ["Node.js", "Next.js", "PostgreSQL"],
    postedDate: "2024-03-12",
    isRemote: true,
    description: "Join our fast-paced team delivering high-scale web apps.",
    responsibilities: ["Maintain backend APIs.", "Integrate frontend with APIs."],
    requirements: ["3+ years React & Node.", "SQL experience."],
    benefits: ["Unlimited PTO", "Remote-first culture"],
  },
  {
    id: "3",
    title: "DevOps Engineer",
    company: "CloudNet",
    logo: "https://cdn-icons-png.flaticon.com/512/906/906324.png",
    location: "Austin, TX",
    salaryRange: "$130k - $170k",
    type: "Contract",
    experience: "Senior",
    tags: ["AWS", "Docker", "Kubernetes"],
    postedDate: "2024-03-05",
    isRemote: false,
    description: "Ensure the reliability of our infrastructure.",
    responsibilities: ["Manage CI/CD pipelines.", "Monitor system health."],
    requirements: ["AWS Certified.", "Python scripting."],
    benefits: ["Health insurance", "Gym stipend"],
  },
  {
    id: "4",
    title: "Backend Go Developer",
    company: "DataStream",
    logo: "https://cdn-icons-png.flaticon.com/512/5969/5969044.png",
    location: "Chicago, IL",
    salaryRange: "$140k - $180k",
    type: "Full-Time",
    experience: "Lead",
    tags: ["Go", "Microservices", "gRPC"],
    postedDate: "2024-03-08",
    isRemote: true,
    description: "Architect scalable backend services in Go.",
    responsibilities: ["Design microservices.", "Optimize database queries."],
    requirements: ["5+ years Backend exp.", "Experience with Go."],
    benefits: ["Stock options", "Remote work allowance"],
  },
];